import 'package:arkanoid/components/brick.dart';
import 'package:arkanoid/components/field.dart';
import 'package:arkanoid/components/levels/base_level.dart';
import 'package:arkanoid/components/power_up.dart';

class Level1 extends BaseLevel {
  Level1() : super(FieldType.blue, 1);

  @override
  Future<void> onLoad() async {
    bricks = [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
      ],
      [
        Brick(BrickModel.red, null),
        Brick(BrickModel.red, null),
        Brick(BrickModel.red, null),
        Brick(BrickModel.red, PowerUp(PowerUpType.extend)),
        Brick(BrickModel.red, null),
        Brick(BrickModel.red, null),
        Brick(BrickModel.red, null),
        Brick(BrickModel.red, null),
        Brick(BrickModel.red, null),
        Brick(BrickModel.red, null),
        Brick(BrickModel.red, null),
        Brick(BrickModel.red, null),
        Brick(BrickModel.red, PowerUp(PowerUpType.extend))
      ],
      [
        Brick(BrickModel.yellow, null),
        Brick(BrickModel.yellow, null),
        Brick(BrickModel.yellow, null),
        Brick(BrickModel.yellow, null),
        Brick(BrickModel.yellow, null),
        Brick(BrickModel.yellow, PowerUp(PowerUpType.cattch)),
        Brick(BrickModel.yellow, null),
        Brick(BrickModel.yellow, null),
        Brick(BrickModel.yellow, null),
        Brick(BrickModel.yellow, null),
        Brick(BrickModel.yellow, PowerUp(PowerUpType.cattch)),
        Brick(BrickModel.yellow, null),
        Brick(BrickModel.yellow, null),
      ],
      [
        Brick(BrickModel.blue, null),
        Brick(BrickModel.blue, null),
        Brick(BrickModel.blue, PowerUp(PowerUpType.cattch)),
        Brick(BrickModel.blue, null),
        Brick(BrickModel.blue, null),
        Brick(BrickModel.blue, null),
        Brick(BrickModel.blue, null),
        Brick(BrickModel.blue, null),
        Brick(BrickModel.blue, null),
        Brick(BrickModel.blue, null),
        Brick(BrickModel.blue, null),
        Brick(BrickModel.blue, null),
        Brick(BrickModel.blue, PowerUp(PowerUpType.slow)),
      ],
      [
        Brick(BrickModel.pink, PowerUp(PowerUpType.slow)),
        Brick(BrickModel.pink, null),
        Brick(BrickModel.pink, null),
        Brick(BrickModel.pink, null),
        Brick(BrickModel.pink, null),
        Brick(BrickModel.pink, null),
        Brick(BrickModel.pink, PowerUp(PowerUpType.slow)),
        Brick(BrickModel.pink, null),
        Brick(BrickModel.pink, null),
        Brick(BrickModel.pink, null),
        Brick(BrickModel.pink, null),
        Brick(BrickModel.pink, PowerUp(PowerUpType.cattch)),
        Brick(BrickModel.pink, null)
      ],
      [
        Brick(BrickModel.green, null),
        Brick(BrickModel.green, PowerUp(PowerUpType.laser)),
        Brick(BrickModel.green, null),
        Brick(BrickModel.green, null),
        Brick(BrickModel.green, PowerUp(PowerUpType.extend)),
        Brick(BrickModel.green, null),
        Brick(BrickModel.green, null),
        Brick(BrickModel.green, null),
        Brick(BrickModel.green, null),
        Brick(BrickModel.green, null),
        Brick(BrickModel.green, null),
        Brick(BrickModel.green, null),
        Brick(BrickModel.green, PowerUp(PowerUpType.extend))
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    ];
    super.onLoad();
  }
}
