import 'package:arkanoid/components/brick.dart';
import 'package:arkanoid/components/field.dart';
import 'package:arkanoid/components/levels/base_level.dart';
import 'package:arkanoid/components/power_up.dart';

class Level4 extends BaseLevel {
  Level4() : super(FieldType.electricRed, 4);

  @override
  Future<void> onLoad() async {
    bricks = [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        Brick(BrickModel.orange, null),
        Brick(BrickModel.lightBlue, null),
        Brick(BrickModel.green, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.blue, PowerUp(PowerUpType.bonus)),
        null,
        Brick(BrickModel.yellow, null),
        Brick(BrickModel.grey, null),
        Brick(BrickModel.orange, null),
        Brick(BrickModel.lightBlue, null),
        Brick(BrickModel.green, null),
        null
      ],
      [
        null,
        Brick(BrickModel.lightBlue, null),
        Brick(BrickModel.green, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.blue, null),
        Brick(BrickModel.pink, null),
        null,
        Brick(BrickModel.grey, null),
        Brick(BrickModel.orange, null),
        Brick(BrickModel.lightBlue, null),
        Brick(BrickModel.green, null),
        Brick(BrickModel.silver, null),
        null
      ],
      [
        null,
        Brick(BrickModel.green, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.blue, null),
        Brick(BrickModel.pink, null),
        Brick(BrickModel.yellow, null),
        null,
        Brick(BrickModel.orange, null),
        Brick(BrickModel.lightBlue, null),
        Brick(BrickModel.green, PowerUp(PowerUpType.cattch)),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.blue, null),
        null
      ],
      [
        null,
        Brick(BrickModel.silver, null),
        Brick(BrickModel.blue, PowerUp(PowerUpType.slow)),
        Brick(BrickModel.pink, null),
        Brick(BrickModel.yellow, null),
        Brick(BrickModel.grey, null),
        null,
        Brick(BrickModel.lightBlue, null),
        Brick(BrickModel.green, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.blue, null),
        Brick(BrickModel.pink, null),
        null
      ],
      [
        null,
        Brick(BrickModel.blue, null),
        Brick(BrickModel.pink, null),
        Brick(BrickModel.yellow, PowerUp(PowerUpType.slow)),
        Brick(BrickModel.grey, null),
        Brick(BrickModel.orange, null),
        null,
        Brick(BrickModel.green, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.blue, PowerUp(PowerUpType.slow)),
        Brick(BrickModel.pink, null),
        Brick(BrickModel.yellow, null),
        null
      ],
      [
        null,
        Brick(BrickModel.pink, null),
        Brick(BrickModel.yellow, null),
        Brick(BrickModel.grey, null),
        Brick(BrickModel.orange, PowerUp(PowerUpType.extend)),
        Brick(BrickModel.lightBlue, null),
        null,
        Brick(BrickModel.silver, null),
        Brick(BrickModel.blue, null),
        Brick(BrickModel.pink, null),
        Brick(BrickModel.yellow, PowerUp(PowerUpType.slow)),
        Brick(BrickModel.grey, null),
        null
      ],
      [
        null,
        Brick(BrickModel.yellow, null),
        Brick(BrickModel.grey, null),
        Brick(BrickModel.orange, null),
        Brick(BrickModel.lightBlue, null),
        Brick(BrickModel.green, null),
        null,
        Brick(BrickModel.blue, null),
        Brick(BrickModel.pink, null),
        Brick(BrickModel.yellow, null),
        Brick(BrickModel.grey, null),
        Brick(BrickModel.orange, PowerUp(PowerUpType.extend)),
        null
      ],
      [
        null,
        Brick(BrickModel.grey, null),
        Brick(BrickModel.orange, PowerUp(PowerUpType.extend)),
        Brick(BrickModel.lightBlue, null),
        Brick(BrickModel.green, null),
        Brick(BrickModel.silver, null),
        null,
        Brick(BrickModel.pink, PowerUp(PowerUpType.laser)),
        Brick(BrickModel.yellow, null),
        Brick(BrickModel.grey, null),
        Brick(BrickModel.orange, null),
        Brick(BrickModel.lightBlue, null),
        null
      ],
      [
        null,
        Brick(BrickModel.orange, null),
        Brick(BrickModel.lightBlue, null),
        Brick(BrickModel.green, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.blue, null),
        null,
        Brick(BrickModel.yellow, PowerUp(PowerUpType.slow)),
        Brick(BrickModel.grey, null),
        Brick(BrickModel.orange, null),
        Brick(BrickModel.lightBlue, null),
        Brick(BrickModel.green, null),
        null
      ],
      [
        null,
        Brick(BrickModel.lightBlue, null),
        Brick(BrickModel.green, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.blue, null),
        Brick(BrickModel.pink, null),
        null,
        Brick(BrickModel.grey, null),
        Brick(BrickModel.orange, null),
        Brick(BrickModel.lightBlue, null),
        Brick(BrickModel.green, null),
        Brick(BrickModel.silver, null),
        null
      ],
      [
        null,
        Brick(BrickModel.green, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.blue, PowerUp(PowerUpType.slow)),
        Brick(BrickModel.pink, null),
        Brick(BrickModel.yellow, null),
        null,
        Brick(BrickModel.orange, null),
        Brick(BrickModel.lightBlue, null),
        Brick(BrickModel.green, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.blue, null),
        null
      ],
      [
        null,
        Brick(BrickModel.silver, null),
        Brick(BrickModel.blue, null),
        Brick(BrickModel.pink, null),
        Brick(BrickModel.yellow, PowerUp(PowerUpType.extend)),
        Brick(BrickModel.grey, null),
        null,
        Brick(BrickModel.lightBlue, null),
        Brick(BrickModel.green, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.blue, PowerUp(PowerUpType.slow)),
        Brick(BrickModel.pink, null),
        null
      ],
      [
        null,
        Brick(BrickModel.blue, null),
        Brick(BrickModel.pink, null),
        Brick(BrickModel.yellow, null),
        Brick(BrickModel.grey, null),
        Brick(BrickModel.orange, null),
        null,
        Brick(BrickModel.green, PowerUp(PowerUpType.cattch)),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.blue, null),
        Brick(BrickModel.pink, null),
        Brick(BrickModel.yellow, null),
        null
      ],
      [
        null,
        Brick(BrickModel.pink, PowerUp(PowerUpType.laser)),
        Brick(BrickModel.yellow, null),
        Brick(BrickModel.grey, null),
        Brick(BrickModel.orange, null),
        Brick(BrickModel.lightBlue, null),
        null,
        Brick(BrickModel.silver, null),
        Brick(BrickModel.blue, null),
        Brick(BrickModel.pink, null),
        Brick(BrickModel.yellow, null),
        Brick(BrickModel.grey, null),
        null
      ]
    ];
    super.onLoad();
  }
}
