import 'package:arkanoid/components/brick.dart';
import 'package:arkanoid/components/field.dart';
import 'package:arkanoid/components/levels/base_level.dart';
import 'package:arkanoid/components/power_up.dart';

class Level5 extends BaseLevel {
  Level5() : super(FieldType.blue, 5);

  @override
  Future<void> onLoad() async {
    bricks = [
      [
        null,
        null,
        null,
        Brick(BrickModel.yellow, PowerUp(PowerUpType.laser)),
        null,
        null,
        null,
        null,
        null,
        Brick(BrickModel.yellow, null),
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        Brick(BrickModel.yellow, null),
        null,
        null,
        null,
        null,
        null,
        Brick(BrickModel.yellow, null),
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        Brick(BrickModel.yellow, null),
        null,
        null,
        null,
        Brick(BrickModel.yellow, null),
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        Brick(BrickModel.yellow, null),
        null,
        null,
        null,
        Brick(BrickModel.yellow, PowerUp(PowerUpType.laser)),
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        null,
        null,
        null
      ],
      [
        null,
        null,
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.red, PowerUp(PowerUpType.extend)),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.red, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        null,
        null
      ],
      [
        null,
        null,
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.red, PowerUp(PowerUpType.laser)),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.red, PowerUp(PowerUpType.break_)),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        null,
        null
      ],
      [
        null,
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        null
      ],
      [
        null,
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        null
      ],
      [
        null,
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        null
      ],
      [
        null,
        Brick(BrickModel.silver, null),
        null,
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        null,
        Brick(BrickModel.silver, null),
        null
      ],
      [
        null,
        Brick(BrickModel.silver, null),
        null,
        Brick(BrickModel.silver, null),
        null,
        null,
        null,
        null,
        null,
        Brick(BrickModel.silver, null),
        null,
        Brick(BrickModel.silver, null),
        null
      ],
      [
        null,
        Brick(BrickModel.silver, null),
        null,
        Brick(BrickModel.silver, null),
        null,
        null,
        null,
        null,
        null,
        Brick(BrickModel.silver, null),
        null,
        Brick(BrickModel.silver, null),
        null
      ],
      [
        null,
        null,
        null,
        null,
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        null,
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        null,
        Brick(BrickModel.silver, null),
        Brick(BrickModel.silver, null),
        null,
        null,
        null,
        null
      ]
    ];
    super.onLoad();
  }
}
