import 'package:arkanoid/components/brick.dart';
import 'package:arkanoid/components/field.dart';
import 'package:arkanoid/components/levels/base_level.dart';
import 'package:arkanoid/components/power_up.dart';

class Level1 extends BaseLevel {
  Level1() : super(FieldType.blue, 1);

  @override
  Future<void> onLoad() async {
    final brickSize = (gameRef.size.x - (Field.hitboxSize * 2)) /
        BaseLevel.numerOfBricEachRow;
    bricks = [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        Brick(BrickModel.silver, null, brickSize),
        Brick(BrickModel.silver, null, brickSize),
        Brick(BrickModel.silver, null, brickSize),
        Brick(BrickModel.silver, null, brickSize),
        Brick(BrickModel.silver, null, brickSize),
        Brick(BrickModel.silver, null, brickSize),
        Brick(BrickModel.silver, null, brickSize),
        Brick(BrickModel.silver, null, brickSize),
        Brick(BrickModel.silver, null, brickSize),
        Brick(BrickModel.silver, null, brickSize),
        Brick(BrickModel.silver, null, brickSize),
        Brick(BrickModel.silver, null, brickSize),
        Brick(BrickModel.silver, null, brickSize),
      ],
      [
        Brick(BrickModel.red, null, brickSize),
        Brick(BrickModel.red, null, brickSize),
        Brick(BrickModel.red, null, brickSize),
        Brick(BrickModel.red, PowerUp(PowerUpType.extend), brickSize),
        Brick(BrickModel.red, null, brickSize),
        Brick(BrickModel.red, null, brickSize),
        Brick(BrickModel.red, null, brickSize),
        Brick(BrickModel.red, null, brickSize),
        Brick(BrickModel.red, null, brickSize),
        Brick(BrickModel.red, null, brickSize),
        Brick(BrickModel.red, null, brickSize),
        Brick(BrickModel.red, null, brickSize),
        Brick(BrickModel.red, PowerUp(PowerUpType.extend), brickSize)
      ],
      [
        Brick(BrickModel.yellow, null, brickSize),
        Brick(BrickModel.yellow, null, brickSize),
        Brick(BrickModel.yellow, null, brickSize),
        Brick(BrickModel.yellow, null, brickSize),
        Brick(BrickModel.yellow, null, brickSize),
        Brick(BrickModel.yellow, PowerUp(PowerUpType.cattch), brickSize),
        Brick(BrickModel.yellow, null, brickSize),
        Brick(BrickModel.yellow, null, brickSize),
        Brick(BrickModel.yellow, null, brickSize),
        Brick(BrickModel.yellow, null, brickSize),
        Brick(BrickModel.yellow, PowerUp(PowerUpType.cattch), brickSize),
        Brick(BrickModel.yellow, null, brickSize),
        Brick(BrickModel.yellow, null, brickSize),
      ],
      [
        Brick(BrickModel.blue, null, brickSize),
        Brick(BrickModel.blue, null, brickSize),
        Brick(BrickModel.blue, PowerUp(PowerUpType.cattch), brickSize),
        Brick(BrickModel.blue, null, brickSize),
        Brick(BrickModel.blue, null, brickSize),
        Brick(BrickModel.blue, null, brickSize),
        Brick(BrickModel.blue, null, brickSize),
        Brick(BrickModel.blue, null, brickSize),
        Brick(BrickModel.blue, null, brickSize),
        Brick(BrickModel.blue, null, brickSize),
        Brick(BrickModel.blue, null, brickSize),
        Brick(BrickModel.blue, null, brickSize),
        Brick(BrickModel.blue, PowerUp(PowerUpType.slow), brickSize),
      ],
      [
        Brick(BrickModel.pink, PowerUp(PowerUpType.slow), brickSize),
        Brick(BrickModel.pink, null, brickSize),
        Brick(BrickModel.pink, null, brickSize),
        Brick(BrickModel.pink, null, brickSize),
        Brick(BrickModel.pink, null, brickSize),
        Brick(BrickModel.pink, null, brickSize),
        Brick(BrickModel.pink, PowerUp(PowerUpType.slow), brickSize),
        Brick(BrickModel.pink, null, brickSize),
        Brick(BrickModel.pink, null, brickSize),
        Brick(BrickModel.pink, null, brickSize),
        Brick(BrickModel.pink, null, brickSize),
        Brick(BrickModel.pink, PowerUp(PowerUpType.cattch), brickSize),
        Brick(BrickModel.pink, null, brickSize)
      ],
      [
        Brick(BrickModel.green, null, brickSize),
        Brick(BrickModel.green, PowerUp(PowerUpType.laser), brickSize),
        Brick(BrickModel.green, null, brickSize),
        Brick(BrickModel.green, null, brickSize),
        Brick(BrickModel.green, PowerUp(PowerUpType.extend), brickSize),
        Brick(BrickModel.green, null, brickSize),
        Brick(BrickModel.green, null, brickSize),
        Brick(BrickModel.green, null, brickSize),
        Brick(BrickModel.green, null, brickSize),
        Brick(BrickModel.green, null, brickSize),
        Brick(BrickModel.green, null, brickSize),
        Brick(BrickModel.green, null, brickSize),
        Brick(BrickModel.green, PowerUp(PowerUpType.extend), brickSize)
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    ];
    super.onLoad();
  }
}
