import 'package:arkanoid/components/brick.dart';
import 'package:arkanoid/components/field.dart';
import 'package:arkanoid/components/levels/base_level.dart';
import 'package:arkanoid/components/power_up.dart';

class Level3 extends BaseLevel {
  Level3() : super(FieldType.electricBlue, 3);

  @override
  Future<void> onLoad() async {
    bricks = [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        Brick(BrickModel.green, PowerUp(PowerUpType.slow)),
        Brick(BrickModel.green, null),
        Brick(BrickModel.green, null),
        Brick(BrickModel.green, null),
        Brick(BrickModel.green, null),
        Brick(BrickModel.green, null),
        Brick(BrickModel.green, PowerUp(PowerUpType.slow)),
        Brick(BrickModel.green, null),
        Brick(BrickModel.green, null),
        Brick(BrickModel.green, null),
        Brick(BrickModel.green, PowerUp(PowerUpType.slow)),
        Brick(BrickModel.green, null),
        Brick(BrickModel.green, PowerUp(PowerUpType.cattch))
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        Brick(BrickModel.grey, null),
        Brick(BrickModel.grey, null),
        Brick(BrickModel.grey, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null)
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        Brick(BrickModel.red, null),
        Brick(BrickModel.red, null),
        Brick(BrickModel.red, PowerUp(PowerUpType.extend)),
        Brick(BrickModel.red, null),
        Brick(BrickModel.red, null),
        Brick(BrickModel.red, null),
        Brick(BrickModel.red, null),
        Brick(BrickModel.red, null),
        Brick(BrickModel.red, null),
        Brick(BrickModel.red, null),
        Brick(BrickModel.red, null),
        Brick(BrickModel.red, PowerUp(PowerUpType.extend)),
        Brick(BrickModel.red, null)
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.grey, null),
        Brick(BrickModel.grey, null),
        Brick(BrickModel.grey, null)
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        Brick(BrickModel.pink, null),
        Brick(BrickModel.pink, null),
        Brick(BrickModel.pink, PowerUp(PowerUpType.slow)),
        Brick(BrickModel.pink, null),
        Brick(BrickModel.pink, null),
        Brick(BrickModel.pink, null),
        Brick(BrickModel.pink, null),
        Brick(BrickModel.pink, null),
        Brick(BrickModel.pink, PowerUp(PowerUpType.slow)),
        Brick(BrickModel.pink, null),
        Brick(BrickModel.pink, null),
        Brick(BrickModel.pink, null),
        Brick(BrickModel.pink, null)
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        Brick(BrickModel.blue, null),
        Brick(BrickModel.blue, null),
        Brick(BrickModel.blue, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null)
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        Brick(BrickModel.lightBlue, null),
        Brick(BrickModel.lightBlue, null),
        Brick(BrickModel.lightBlue, null),
        Brick(BrickModel.lightBlue, null),
        Brick(BrickModel.lightBlue, null),
        Brick(BrickModel.lightBlue, PowerUp(PowerUpType.cattch)),
        Brick(BrickModel.lightBlue, PowerUp(PowerUpType.cattch)),
        Brick(BrickModel.lightBlue, null),
        Brick(BrickModel.lightBlue, null),
        Brick(BrickModel.lightBlue, PowerUp(PowerUpType.extend)),
        Brick(BrickModel.lightBlue, null),
        Brick(BrickModel.lightBlue, null),
        Brick(BrickModel.lightBlue, null)
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.gold, null),
        Brick(BrickModel.lightBlue, null),
        Brick(BrickModel.lightBlue, PowerUp(PowerUpType.extend)),
        Brick(BrickModel.lightBlue, null)
      ]
    ];
    super.onLoad();
  }
}
